### ISSUE TITLE
if you just return it passes

### ISSUE THREAD

**Issue by Lagicrus** [portsoc/js201#8]
following on from #7 during the creation of divisors if i only return'd I passed the test
```js
function divisors(array, divisor){
return
}
![image](https://user-images.githubusercontent.com/24227350/46258587-492baa80-c4c5-11e8-8975-92805aba32d0.png)

**Comment by Hopson97** [comment]
From the Moodle page:

"Notice that some of the tests use a compare function. One of your tasks is to write that function, so you should recognise that any tests which use it cannot pass until it is written and correct! :-)"

**Comment by jacekkopecky** [comment]
I can't replicate this, let's have a look in the labs, or please send me your file (assuming you didn't change anything in the tests).

**Comment by Lagicrus** [comment]
Alright, will do
Worth mentioning that for some reason when I was running my code it had major issues connecting to your subdomain, however I am assuming that's due to the fact I was running it at home and not on a uni VM when I was coding this

**Comment by jacekkopecky** [comment]
Hi, did we ever get back to this? Is this issue still worth keeping open?

**Comment by ear1grey** [comment]
Unsure.  Open depends on how we use it next year.
