### ISSUE TITLE
looks like thare is a bug with the unit tests 🤦

### ISSUE THREAD

**Issue by UP822718** [portsoc/js201#9]
![image](https://user-images.githubusercontent.com/36608060/46374847-a5d7c280-c689-11e8-8a5b-54382ce75045.png)
only done the basic and multiples and divisors.
tested on Firefox 62.0 on Linux Mint X86_64.

**Comment by UP822718** [comment]
oh i see

**Comment by ear1grey** [comment]
Can you please clarify what this issue is?
What are you expecting to see, and how does what you observe differ from this?
